version: "3.9"
services:  
  prefect-agent-google-iap:
    image: phucdinh/google-play-iap:v1.0.1
    container_name: prefect-agent-google-iap
    restart: unless-stopped
    entrypoint: ["prefect", "agent", "start", "-q", "COMPANY_PC_VOLIO_IAP"]
    env_file:
      - .env
