version: "3.9"
services:  
  d_wallpaper:
    image: phucdinh/adjust_transform_raw_csv:2023-04-14
    container_name: d_wallpaper 
    profiles:
      - govo
      - d_wallpaper
    restart: unless-stopped
    entrypoint: ["prefect", "agent", "start", "-q", "d_wallpaper"]
    environment:
      - PREFECT_API_URL=${PREFECT_API_URL}
      - PREFECT_API_KEY=${PREFECT_API_KEY}
      - APP_NAME=${d_wallpaper_APP_NAME}
      - SERVICE_ACCOUNT=${d_wallpaper_SERVICE_ACCOUNT}
      - BUCKET_NAME=${d_wallpaper_BUCKET_NAME}
      - PROJECT_ID=${d_wallpaper_PROJECT_ID}
      - DATASET=${d_wallpaper_DATASET}


